language: ruby
rvm:
  - 2.3
before_script:
  - chmod +x ./script/cibuild
  - bundle exec jekyll build
  - gem install html-proofer
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build
addons:
  apt:
    packages:
      - libssl1.0.0
