# Site settings
title: Alex Luoyuan Xiong
subtitle: a blog of Alex Xiong
email: veralexxiong@outlook.com
author: Luoyuan Alex Xiong
description: >-
  Website/Blog of Alex Luoyuan xiong, a blockchain developer and a cryptography lover.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ALuoyuan
github_username:  AlexXiong97

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 1..2
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highligher: rouge
timezone: Asia/Singapore
excerpt_separator: <!--more-->
future: true
permalink: /:categories/:title/
# Exclude from processing.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', vendor]
editor: gvim
git:
  branch: master
category_archive:
  slugify: true
plugins:
  - jekyll-seo-tag
