# Site settings
title: Alex Luoyuan Xiong
subtitle: a blog of Alex Xiong
email: veralexxiong@outlook.com
author: Luoyuan Alex Xiong
description: >-
  Website/Blog of Alex Luoyuan xiong, a blockchain developer and a cryptography lover.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexxiong.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ALuoyuan
github_username:  AlexXiong97

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 1..2
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highligher: rouge
timezone: Asia/Singapore
excerpt_separator: <!--more-->
future: true
# Exclude from processing.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', vendor]
plugins:
  - jekyll-seo-tag
sass:
  load_paths:
    - _sass
    - css
    - node_modules
  style: compressed
exclude:
  - node_modules
  - README.md
  - LICENSE.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - script
  - spec
  - vendor
include:
  - _pages