# Site settings
title: Semantic Crypto
subtitle: a blog of Alex Xiong
email: veralexxiong@outlook.com
author: Luoyuan Alex Xiong
description: >-
  This is a collection of my thoughts, works and blog posts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ALuoyuan
github_username:  AlexXiong97

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highligher: rouge
timezone: Asia/Singapore
excerpt_separator: <!--more-->
# Exclude from processing.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
category_archive:
  slugify: true
