#!/usr/bin/env ruby
require 'rubygems'
require 'rake'
require 'rdoc'
require 'date'
require 'yaml'
require 'tmpdir'
require 'jekyll'
require 'html-proofer'

Jekyll::Site.new(Jekyll.configuration({
    "source"      => "../",
    "destination" => "_site"
  })).process

# Check missing img, wrong external and internal links.
HTMLProofer.check_directory("../_site", {
  :empty_alt_ignore => true,
  :http_status_ignore => [999]
  }).run
