#!/usr/bin/env ruby
require "html-proofer"

# add links to ignore here
url_ignores = [
  %r{https://localhost:*/*}, # Ignore links to localhost in documentation
  %r{https://*ncl.sg/*},
]

begin
  HTMLProofer::Runner.new(["_site"],
    :type => :directory,
    :url_ignore => url_ignores,
    :verbose => !!ENV["VERBOSE"],
    :check_html => true,
    :empty_alt_ignore => true,
    :http_status_ignore => [999],
    :typhoeus => {
      # Work around SSL errors: https://github.com/gjtorikian/html-proofer/issues/376
      :ssl_verifypeer => false,
      :ssl_verifyhost => 0
    }
  ).run
rescue => e
  puts "\n", e
  exit 1
end
